---
.pdkignore:
  paths:
    - '/.fixtures.yml'
    - '/.gitattributes'
    - '/.gitignore'
    - '/.gitlab-ci.yml'
    - '/.pdkignore'
    - '/.rspec'
    - '/.rubocop.yml'
    - '/.travis.yml'
    - '/.yardopts'
    - '/appveyor.yml'
    - '/Dockerfile'
    - '/Gemfile'
    - '/Rakefile'
    - '/spec/'
.travis.yml:
  docker_sets:
  docker_defaults:
    # values will replace @@SET@@ with the docker_sets' value
  - rvm: 2.5.3
    services: docker
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=@@SET@@ BEAKER_HYPERVISOR=docker CHECK=beaker
    bundler_args: --without development release
  - rvm: 2.5.3
    services: docker
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=@@SET@@ BEAKER_HYPERVISOR=docker CHECK=beaker
    bundler_args: --without development release
  includes:
  - rvm: 2.4.4
    env: PUPPET_VERSION="~> 5.0" CHECK=test
    bundler_args: --without system_tests development release
  - rvm: 2.5.3
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
    bundler_args: --without system_tests development release
  - rvm: 2.5.3
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
    bundler_args: --without system_tests development release
  - rvm: 2.4.4
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
    bundler_args: --without system_tests development release
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
    - "chat.freenode.org#voxpupuli-notifications"
  user: puppet
Gemfile:
  required:
    ':test':
      - gem: rspec-puppet-utils
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-version_comparison-check
      - gem: puppet-lint-classes_and_types_beginning_with_digits-check
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: puppet-lint-absolute_classname-check
      - gem: redcarpet
      - gem: parallel_tests

      - gem: 'puppet-module-posix-default-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-posix-dev-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-default-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: 'puppet-module-win-dev-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
    ':development':
      - gem: travis
      - gem: travis-lint
      - gem: guard-rake
      - gem: overcommit
        version: '>= 0.39.1'
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw

      - gem: winrm
      - gem: rbnacl
        version: '>= 4'
      - gem: rbnacl-libsodium
      - gem: bcrypt_pbkdf
    ':release':
      - gem: github_changelog_generator
        git: https://github.com/github-changelog-generator/github-changelog-generator
      - gem: voxpupuli-release
        git: https://github.com/voxpupuli/voxpupuli-release-gem
Rakefile:
  config.user: voxpupuli
  exclude_paths: []
  puppet_lint_checks: []
  puppet_strings_patterns: []
spec/spec_helper.rb:
  mock_with: ':rspec'
spec/spec_helper.rb:
  strict_level: ":warning"
...
# vim: syntax=yaml
